version: "3.7"

services:
    pg-primary:
        image: postgres:12.2
        # restart: always
        env_file: .pg_env
        volumes:
            - ./postgres_primary_data:/var/lib/postgresql/data
        ports:
            - "5432:5432" #for debugging
        networks:
            postgres-network:
                ipv4_address: 172.21.0.2
    
    pg-replica:
        image: postgres:12.2
        env_file: .pg_env
        volumes:
            - ./postgres_replica_data:/var/lib/postgresql/data
        ports:
            - "8000:5432" #for debugging
        depends_on:
            - pg-primary
        networks:
            postgres-network:
                ipv4_address: 172.21.0.3

networks:
    postgres-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.21.0.0/16