version: "3.7"

services:
    pg-primary:
        image: postgres:12.2
        # restart: always
        env_file: .pg_env
        volumes:
            - ./postgres_primary_data:/var/lib/postgresql/data
            - ./primary_vol:/app
        ports:
            - "5432:5432" #for debugging
        command: bash -c "rm -rf /var/lib/postgresql/data/* &&
                          chown -R postgres:postgres /var/lib/postgresql/data &&
                          su postgres -c \"pg_ctl init &&
                          echo host replication all 172.21.0.3/32 trust >> /var/lib/postgresql/data/pg_hba.conf &&
                          pg_ctl start &&
                          psql -f /app/add_replication_user.sql &&
                          echo wal_level = replica >> /var/lib/postgresql/data/postgresql.conf &&
                          echo max_wal_senders = 10 >> /var/lib/postgresql/data/postgresql.conf &&
                          echo max_replication_slots = 10 >> /var/lib/postgresql/data/postgresql.conf &&
                          echo synchronous_commit = off >> /var/lib/postgresql/data/postgresql.conf &&
                          pg_ctl restart &&
                          psql -f /app/add_replication_slot.sql &&
                          pg_ctl stop &&
                          postgres\""
        networks:
            postgres-network:
                ipv4_address: 172.21.0.2
    
    pg-replica:
        image: postgres:12.2
        env_file: .pg_env
        volumes:
            - ./postgres_replica_data:/var/lib/postgresql/data
            - ./replica_vol:/app
        ports:
            - "8000:5432" #for debugging
        depends_on:
            - pg-primary
        command: bash -c "echo 172.21.0.2:5432:testdb:repuser:testpass > /var/lib/postgresql/.pgpass && 
                          chmod 0600 /var/lib/postgresql/.pgpass &&
                          chown -R postgres:postgres /var/lib/postgresql/data &&
                          rm -rf /var/lib/postgresql/data/* && 
                          sleep 2 &&
                          su postgres -c \"/app/init_pg.sh\""
        networks:
            postgres-network:
                ipv4_address: 172.21.0.3

networks:
    postgres-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.21.0.0/16