version: "3.7"

services:
    pg-primary:
        image: postgres:12.2
        # restart: always
        env_file: .pg_env
        volumes:
            - ./postgres_primary_data:/var/lib/postgresql/data
        ports:
            - "5432:5432" #for debugging
        networks:
            postgres-network:
                ipv4_address: 172.21.0.2
    
    pg-replica:
        image: postgres:12.2
        env_file: .pg_env
        volumes:
            - ./postgres_replica_data:/var/lib/postgresql/data
        ports:
            - "8000:5432" #for debugging
        depends_on:
            - pg-primary
        command: bash -c "echo 172.21.0.2:5432:testdb:repuser:testpass > /var/lib/postgresql/.pgpass && 
                          chmod 0600 /var/lib/postgresql/.pgpass &&
                          chown -R postgres:postgres /var/lib/postgresql/data &&
                          rm -rf /var/lib/postgresql/data/* && 
                          su postgres -c \"pg_basebackup -h 172.21.0.2 -D /var/lib/postgresql/data -U repuser -vP -w && 
                          touch /var/lib/postgresql/data/standby.signal &&
                          echo primary_conninfo = \'host=172.21.0.2 port=5432 user=repuser password=testpass application_name=r1\' >> /var/lib/postgresql/data/postgresql.conf &&
                          echo primary_slot_name = \'replica_1_slot\' >> /var/lib/postgresql/data/postgresql.conf &&
                          postgres\""
        networks:
            postgres-network:
                ipv4_address: 172.21.0.3

networks:
    postgres-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.21.0.0/16